services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tourze\HttpRequestTaskBundle\DataFixtures\:
        resource: '../../DataFixtures/'
        tags: ['doctrine.fixture.orm']